import React from 'react'

export const FaqData = [
    {title: "What is a vehicle wrap?", content: "There are two categories of vehicle wraps, color change wraps and commercial wraps. Color change wraps are an affordable alternative to painting your vehicle. The vinyl wrap media comes in about any color you can think of and is installed directly to the vehicle. In many cases, our vehicle wraps have been mistaken for custom paint jobs. Commercial wraps consist of a design that is printed on our HP Latex onto the highest quality vinyl. The print is then laminated to prolong the lifespan of the wrap and then applied to your vehicle."},
    {title: "How much is a vehicle wrap?", content:"Vehicle wraps vary in price. At Elite Wraps, we price the work based on the square footage of media being utilized for the job and based on the complexity of the vehicle."},
    {title: "Do we offer design services?", content:"We do have a design team with decades of experience in vehicle wrap designs and more. Our design team will work with you throughout the design process until the you are satisfied the outcome."},
    {title: "How are the graphics printed?", content:"Our team takes the graphic file for that vehicle and brings it to scale based on the measurements taken of that vehicle. The graphics are then printed on our large format printer."},
    {title: "How long does a vehicle wrap take?", content:"It does depend on the complexity of the vehicle and the amount of vinyl used to wrap the vehicle. Typically, once graphics have been approved we estimate one week for install. However, we know how important having a vehicle is so we can work with your schedule to relieve you of as much inconvenience as possible"},
    {title: "Can a vehicle wrap be removed?", content:"The majority of wraps can be removed. We primarily use a non-permanent vinyl that can be removed fairly easily if it was properly maintained. We still do advise that you have a professional remove it to avoid any unnecessary damages that may occur"},
    {title: "How long does a vehicle wrap last?", content:"It does depend on the quality of material used for the wrap, the conditions the wrap is exposed to, and how well the wrap is maintained. Here at Elite Wraps, we only use the highest quality vinyl, so they should last between 7-10 years. We also recommend hand washing wrapped vehicles to help maintain and prolong the wrap."},
]