export const vehicleMakeOptions = [
    { value: "Make", label: "Make"},
    { value: "Abarth", label: "Abarth"},
    { value: "Acura", label: "Acura"},
    { value: "Alfa Romeo", label: "Alfa Romeo"},
    { value: "Aston Martin", label: "Aston Martin"},
    { value: "Audi", label: "Audi"},
    { value: "Bentley", label: "Bentley"},
    { value: "BMW", label: "BMW"},
    { value: "Buick", label: "Buick"},
    { value: "Cadillac", label: "Cadillac"},
    { value: "Chevrolet", label: "Chevrolet"},
    { value: "Chrysler", label: "Chrysler"},
    { value: "Citroen", label: "Citroen"},
    { value: "Dacia", label: "Dacia"},
    { value: "Dodge", label: "Dodge"},
    { value: "Farrari", label: "Farrari"},
    { value: "Fiat", label: "Fiat"},
    { value: "Ford", label: "Ford"},
    { value: "GMC", label: "GMC"},
    { value: "Honda", label: "Honda"},
    { value: "Hummer", label: "Hummer"},
    { value: "Hyundai", label: "Hyundai"},
    { value: "Infiniti", label: "Infiniti"},
    { value: "Isuzu", label: "Isuzu"},
    { value: "Jaguar", label: "Jaguar"},
    { value: "Jeep", label: "Jeep"},
    { value: "Kia", label: "Kia"},
    { value: "Lamborghini", label: "Lamborghini"},
    { value: "", label: ""},
]
export const vehicleModelOptions = [
    { value: "Model", label: "Model"},
    { value: 2000, label: 2000},
]
export const vehicleColorOptions = [
    { value: "Color", label: "Color"},
    { value: 2000, label: 2000},
]